### PR TITLE
New tskit

### PR DESCRIPTION
**Pull request by petrelharp**
Here's the new `tskit` code.  The most notable changes are:

- substantially changing what columns are in the IndividualTable
- adding an `individual` column to the NodeTable

I've got most of the required changes in.  Still to-do:

1. rewrite code to load in tables to use the new individual table scheme
2. set the `individual` column in the node table appropriately when writing the individual table

Also:

3. (possibly) remove the stuff we store in the `provenance table` and put it instead into the `kastore` directly.

This latter is I think a good idea *except* that then it becomes unclear how we would store this stuff in text input/output.  So maybe we leave well enough alone.

I've also included more of the files in `tskit` than were here before, the Xcode stuff will need updating.

cc @bhaller @jgallowa07

### CODE REVIEW

**Comment by bhaller** [comment]
OK, sounds great.  Shall we merge this stuff in?  I'm hungry to get it, and I'm fine with 1 and 2 remaining un-done right now.  Re: 3, I guess in text input/output it would become a new file?  But that seems unnecessary, and I don't see a problem with SLiM-specific stuff being in a SLiM provenance entry, so I'd leave well enough alone as you say.

**Comment by bhaller** [comment]
I'll patch up the Xcode project immediately if you merge this in, no worries on that.

**Comment by bhaller** [comment]
Ah, I know what you're going to say, I should just use this branch.  Which is true.  OK, I just checked out a copy of it.  :->

**Comment by bhaller** [comment]
OK, so, trying to get this to build under Xcode.  You added this to slim_sim.cpp:

#include "../treerec/tskit/text_output.h"

but that header does not appear to be included in the repository at all (in petrelharp/SLiM, new_tskit branch; that's what I should be working with, right?).

**Comment by petrelharp** [comment]
Whoops - that was a typo - should be `text_input.h`.  I guess I don't need that line there...

**Comment by petrelharp** [comment]
Feel free to merge; just this is not currently compiling so I didn't want to break things.

**Comment by jaredgalloway** [comment]
Ok, merged, What's the status on all the tests files .. should those be ignored for a build to work?

**Comment by bhaller** [comment]
"provenance_table_dump_text" is used but does not appear to be defined in any file presently in the repository; is there a file missing from the commit, or am I doing something wrong?  And then there are a bunch of build errors in SLiMSim::__TabulateSubpopulationsFromTreeSequence (my code that doesn't yet run) which seem to be because the fields contained by the individual table have completely changed; I'm not sure what to do about all the individual table fields I was using, where did they go?  I am in need of some guidance, I have lost the thread of what has happened here.  Anyway, I patched up a few things that weren't working under Xcode and committed them; I'm not sure how to proceed further.

**Comment by bhaller** [comment]
(Not sure which tests files you mean, I suspect I am not including them in the Xcode project right now; I'm only adding files when there seems to be a link dependency on something that hasn't been included yet.)

**Comment by bhaller** [comment]
Also, you seem to have removed `newick.c` from the repository, but `sparse_tree_get_newick()` in `tree_sequence.c` still seems to reference the newick stuff, so I'm not sure what your intention is there.  I just commented out `sparse_tree_get_newick()` entirely, since it seems to be unused in the SLiM project.  I also commented out all of my code for loading in from `.trees` files, since it was all failing to build now; that can be returned to once everything else is working.  And I commented out the call to `provenance_table_dump_text()` since that function didn't seem to exist, so now we don't write out the provenance table when writing text.  I added `#warning` directives in all these spots so that they don't get lost in the shuffle.  With those changes, it built and ran, but there was a crasher inside `SLiMSim::WriteIndividualTable()`, which I fixed by adding `location_offset.push_back(0);`.  I've just committed all those changes.  Now I'll see whether I can do some tree-seq runs and write out .trees files that msprime can read!  :->

**Comment by petrelharp** [comment]
Sorry about the breakage; I'd left this as a pull request because it was still broken.  This is now a funny place to discuss these things, since this PR is closed, but here goes anyhow.

> provenance_table_dump_text()

Whoops, my fault.

> newick.c

Ditto.

> changes to individual table

See discussion over [here](https://github.com/tskit-dev/msprime/pull/472) for the format of an individual table.  As you can see [here](https://github.com/jgallowa07/SLiM/pull/6/files#diff-164c8a503989aafdda54a6ad5ffc8b9fR4555) I've added age and subpop to the individual metadata struct; and sex is going into the flags.

But, since this PR is closed, I'm going to continue discussion of this elsewhere, probably in comments on my commits.

**Comment by bhaller** [comment]
No worries re: breakage, I asked for it.  :->  It let me get that figure finished for Jerome.

Re: newick.c, I have reinstated the ban on sparse_tree_get_newick() because in your commit you did not actually add that file back in to the repository.  So it is missing on my side, and can't be added to the Xcode project, and thus the build is still broken.  So when you reinstate sparse_tree_get_newick(), you need to also re-add newick.c to GitHub.  Probably I could have dug that file out from somewhere, but I didn't want to risk introducing the wrong version of it, etc., since I don't even know what a "newick" is.  :->

**Pull request merged**
